### ISSUE TITLE
Inside of "e" is slanted 

### ISSUE THREAD

**Issue by seanfrasure** [google/roboto#180] opened 2016-05-18 17:19 UTC
Got this on mobile:
![img_20160518_131844](https://cloud.githubusercontent.com/assets/9723817/15368305/20241c5e-1cfb-11e6-8ed1-4cf3b29f1ee2.JPG)
Its only with lowercase ...

**Comment by jamesgk** [comment] 2016-06-01 01:04
Yikes. Can you provide more details as to where you saw this? Any particular app / device / Android version? I can't reproduce myself.

**Comment by seanfrasure** [comment] 2016-06-01 11:27
Android Version: Android 4.2.2
App: Google Chrome

**Comment by jamesgk** [comment] 2016-06-13 23:11
Duplicate of https://github.com/google/roboto/issues/181

**Closed by jamesgk** 2016-06-13 23:11 UTC
