### ISSUE TITLE
Please consider reopening issue #243 - Font x-height is now incorrect on Windows platforms

### ISSUE THREAD

**Issue by thesilentw** [google/roboto#244] opened 2017-04-19 05:19 UTC
Quoting the original issue - 
+++
Going from v15 to v16 (fonts.google.com) changes the height of lower case letters. Anyone using a https://fonts.googleapis.com/css?family=Roboto link on their website will suddenly see a significant and possibly very unwanted difference.
+++

I find it VERY concerning that this issue, which affects more than a third of Chrome's userbase, is now considered a 'feature', simply because it's been in the testing repository for a few years. What kind of precedent does this set?
This issue breaks font display in a significant and easily noticeable manner on almost every website, for every Windows Chrome user. Why was the original issue closed? This is a severe lack of transparency and review on a very serious issue.

**Comment by designerdd** [comment] 2017-04-19 06:01
Agreed. Changing the characteristics of a font that whole sites are designed around so that it looks different for a huge % of the userbase and leaving it as good enough is strange and irresponsible. 

You've broken site layouts with this mistake (and it IS a mistake now, not a "feature"). Is it the users fault for trusting you to keep a font loading consistently I suppose?

**Comment by atomicthumbs** [comment] 2017-04-19 06:53
Fonts should not change without the permission of the users, regardless of whether the appearance that's been delivered consistently is a bug or not.

**Comment by m4rc1e** [comment] 2017-04-19 08:26
>I find it VERY concerning that this issue, which affects more than a third of Chrome's userbase, is now considered a 'feature', simply because it's been in the testing repository for a few years. What kind of precedent does this set?

I already reported this issue, #236, whilst working on the update. The [testing repo](https://github.com/googlefonts/robototester/releases) is purely to demonstrate the hinting differences in MDL on different platforms. Its existed for a month or so :-). The pr made to google/fonts, https://github.com/google/fonts/pull/710 also extensively highlights this hinting change. 

Why the change?
The previous v2.000 webfonts were released 2015-01-15, which contained broken hinting, #68. The issue was resolved when the 3rd party who hinted the fonts updated the cvt values to match the v1.000 release. This happened around June 2015. The new v2.137 release has the hinting cvt fix to bring the bring the family back in line with the v1.000 release.

**Comment by davelab6** [comment] 2017-04-19 12:52
I closed it because it will not be rolled back, nor will there be another
update in the future changing the hinting again any time soon.

I'm sorry you disagree that the changes are an improvement but I stand
behind that 100% :)

If you enjoy total control, the libre license of every font available from
the Google Fonts directory enables you to self host, and I encourage you to
do so.

**Comment by ymgve** [comment] 2017-04-19 14:12
This is not a small change, this feels like an entirely new font.

**Comment by davelab6** [comment] 2017-04-19 15:57
You are free to self-host the old version :)

**Closed by davelab6** 2017-04-19 15:58 UTC

**Comment by Rinux55** [comment] 2017-04-20 07:29
With the update, the font works well on most sizes. Just when it is put to 12px it looks like you have Roboto Narrow, completely changing the characteristics of the font. I agree with most people here that this is a bug.

**Comment by Rinux55** [comment] 2017-04-21 09:16
@davelab6  where can I find the old .woff file? I will take your advice and self-host it.

**Comment by Wladkh** [comment] 2017-04-24 14:20
@davelab6 I agree with the guys, in this variant the font can not be left ... It is not displayed correctly ...
Tell me, is it possible to specify the version in "https://fonts.googleapis.com/css?family=Roboto:400,900&subset=latin,cyrillic&version=15" to be downloaded from googleapis, but the old version.

**Comment by user23145** [comment] 2017-05-01 04:01
Disappointing that this won't be changed. The readability of the font is now significantly worse.

**Comment by davelab6** [comment] 2017-05-01 13:43
Please explain why you think it is worse; I believe the increased xheight
makes it better

On May 1, 2017 12:02 AM, "user23145" <notifications@github.com> wrote:

Disappointing that this won't be changed. The readability of the font is
now significantly worse.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/google/roboto/issues/244#issuecomment-298282603>, or mute
the thread

**Comment by Wladkh** [comment] 2017-05-01 17:30
> Please explain why you think it is worse; I believe the increased xheight makes it better

davelab6, sorry that I'm wedging in, but it's about the fact that only in Windows it's stretched. In other operating systems that I used, for example, Android, the font is normal.

Look, what's the difference in Windows:
http://fs2.fex.net/show/643339124536/10816915/badwinroboto.gif?1600w
Read unpleasant when so stretched.

For example, in Android font is not stretched. While the stretched font I watch only in Windows.

**Comment by user23145** [comment] 2017-05-01 18:38
I'm experiencing the same problems as @Wladkh is. It looks incredibly stretched (vertically) and compressed (horizontally) on all of my sites (using Windows OS). 

It no longer looks like the same font. It looks more like a condensed version of Roboto.

**Comment by davelab6** [comment] 2017-05-02 04:11
> where can I find the old .woff file? I will take your advice and self-host it.

The WOFF file isn't available here, but you can create one with the usual tools if you get the old TTF file from the git history... eg if you go to

https://github.com/google/fonts/tree/91841512c998146de55adeeff193f3f25dafdc44/apache/roboto

and

https://github.com/google/fonts/tree/91841512c998146de55adeeff193f3f25dafdc44/apache/robotocondensed

and click the TTF and then 'view raw' you'll download the file.

**Comment by davelab6** [comment] 2017-05-02 13:39
> And if the text is wider, then the eye will lose a line of text. So it will be necessary to change the line spacing for Windows OS specifically.

The line spacing could be adjusted, but no text line should be longer than before. 

> It looks more like a condensed version of Roboto

In vector outlines, Roboto looks condensed; I think previously it was being shown artificially wide.

**Comment by Wladkh** [comment] 2017-05-02 16:31
> The line spacing could be adjusted, but no text line should be longer than before.
@davelab6 I did not mean the length of the current text. I said if the text is longer, then it's harder to read. It is necessary to increase the line spacing. Here's an example:
<img src="http://fs3.fex.net/get/776431266435/10948408/badwinroboto2.gif">
A new line is lost when reading.

Do not you want to make the old version of Roboto loaded for Windows? Or somehow remake? After all, this is a mistake if it is displayed normally in other operating systems, but not in Windows. I do not know how others, but I think it's a mistake when the text, for example, in Android is very different from Windows.

I have to give up the conventional values (em), because It is necessary to exclude even font sizes (16/18).

**Comment by davelab6** [comment] 2017-05-02 18:25
aha! I think you mean rather than

> I said if the text is longer, then it's harder to read. It is necessary to increase the line spacing.

you mean

> I said if the text is **taller**, then it's harder to read. It is necessary to increase the line spacing.

But I simply disagree; I think the text being taller makes it **easier** to read, because the counters have more space inside them. 

When I look at your image, and the proportions of the "R" and "o" in the first word, compared to the rendering on this Mac OS X laptop I am using, I think the one on the right is closer to the Mac rendering. 

![screen shot 2017-05-02 at 14 24 39](https://cloud.githubusercontent.com/assets/261579/25632823/1d5d7ba4-2f43-11e7-9721-0920c79d30b4.png)

**Comment by Wladkh** [comment] 2017-05-03 02:14
Look at what I get. Font 18 is the same in Windows, and 16 are stretched:
<img src="http://fs3.fex.net/get/792821046648/11012699/baditem3.jpg">

**Comment by davelab6** [comment] 2017-05-03 03:49
Yes - stretches down in the old version.

**Comment by StreetStrider** [comment] 2022-12-03 16:27
![line-height2](https://user-images.githubusercontent.com/2124761/205451103-b4d569dc-a67f-4cc6-8687-f4e9d36f807c.png)

Am I facing this exact issue? I've noticed that baseline is visibly higher at Windows. First I thought that this is Windows rendering issue, but according to this thread this is happening only in Chrome browser. I can confirm that in Firefox on Windows this is not the case.
I've tried both to bundle the font and to get it from cdn. If the platform is Windows and the browser is Chrome the pic is what is happening.

**Comment by thesilentw** [comment] 2022-12-04 20:40
> Am I facing this exact issue? I've noticed that baseline is visibly higher at Windows. First I thought that this is Windows rendering issue, but according to this thread this is happening only in Chrome browser. I can confirm that in Firefox on Windows this is not the case. I've tried both to bundle the font and to get it from cdn. If the platform is Windows and the browser is Chrome the pic is what is happening.

And the stake-pit finds a new victim...
Yep, this is the issue you're seeing. Please, read the thread and bask in what "open-source" development apparently means to google. It turns out that if you don't work for google, you don't get a vote or an opinion on... anything, really. Amazing that they haven't nuked this thread, as it's quite a damming piece of evidence...
