### ISSUE TITLE
Roboto fonts not usable in Microsoft Windows enviroment

### ISSUE THREAD

**Issue by mchowdhury** [google/roboto#37] opened 2015-05-26 20:05 UTC
What steps will reproduce the problem?
1. Install the Roboto fonts family (Windows 7, Windows 8, Windows 8.1)
2. Start using Microsoft Word (2010/2013)
3. Select Roboto Fonts

What is the expected output? What do you see instead?
Word shows only "Roboto" in the Fonts selector and uses only the first installed fonts type. Even so it is possible to select another type in the fonts property menu the chosen type is not shown/used.

https://code.google.com/p/googlefontdirectory/issues/detail?id=233

**Comment by codeman38** [comment] 2015-05-26 20:21
More specifically, this is an issue with the `name` table.

There are 2 places that the family name and style name are present in the name table:
* ID 1, 2: family and style name for compatibility with environments such as Windows that only allow four base styles per family.
* ID 16, 17: family and style name for environments that support additional styles.

For any fonts outside of the base 4 styles (Regular, Italic, Bold, Bold Italic), name record 1 should include the weight name, while name record 2 should only contain "Regular" or "Italic".

This has been corrected in the files at https://github.com/google/fonts/tree/master/apache/roboto, but that fix doesn't seem to have made it to this repository yet.

**Comment by chrtz** [comment] 2015-07-05 22:24
Thanks codeman, 
sadly I still have the issue that the regular italic isn't recognized by windows. :/

**Comment by codeman38** [comment] 2015-08-21 14:21
This still isn't fixed in the binary deliveries as of 2015/08/20 (545be2d). Were the binaries generated using the code from #51?

I wrote a Python script a while back which uses fonttools to fix the `name` tables in the binaries as specified above, and it still appears to work on the latest deliveries: https://gist.github.com/codeman38/9d77f650a875639a55e6

**Comment by jamesgk** [comment] 2015-08-21 17:28
Unfortunately no, the binaries present in the repository are not generated by the latest scripts. So yea, the choices are basically to either hotfix the existing binaries as you've done, or generate new fonts from the toolchain yourself (which *should* be functionally identical to the existing binaries, but the fact that we aren't yet fully confident of this is why this discrepancy exists).

**Comment by jamesgk** [comment] 2016-03-17 23:54
This should be fixed (finally!) in the latest release: https://github.com/google/roboto/releases

**Closed by jamesgk** 2016-03-17 23:54 UTC

**Comment by Battlehorn** [comment] 2016-04-28 12:43
The version was 2.132......roboto regular problem is still not fixed..

**Comment by jamesgk** [comment] 2016-04-28 18:38
I'm unable to reproduce this issue on Windows 8.1 with the fonts in roboto-hinted.zip from the latest release. Could you give some details about where you're seeing a problem?

**Comment by davelab6** [comment] 2016-04-28 19:19
Maybe make sure to uninstall any previous copies?

**Comment by czuboka** [comment] 2016-07-05 20:06
A client of mine has started using Roboto in Microsoft Office on Windows machines, and are having problems with the way the font is rendering on screen. The font is displaying very poorly and is nearly impossible to read without zooming in quite a ways. Has anyone encountered this issue? Client sent me this screen shot showing the different between how Roboto displays vs Arial.

![arialvsroboto](https://cloud.githubusercontent.com/assets/20307035/16598093/1ab20e76-42b1-11e6-88b9-c814f5229d8e.png)

**Comment by jamesgk** [comment] 2016-07-06 17:14
@czuboka my first impression is that this looks like unhinted Roboto. Could you first make sure that your client is using the hinted version of Roboto? Thanks.

**Comment by czuboka** [comment] 2016-07-08 17:30
@jamesgk can you provide me a link to the latest version with hinting so I can be sure I am sending my client the best solution. There are a lot of variations floating around. Thanks!

**Comment by jamesgk** [comment] 2016-07-08 18:52
The latest version of Roboto can be found at https://github.com/google/roboto/releases; the current version with hinting is https://github.com/google/roboto/releases/download/v2.134/roboto-hinted.zip.
