### ISSUE TITLE
Getting a "markClass @MC_mark_parent_top and @MC_mark_top" error building OpenType

### ISSUE THREAD

**Issue by pereljon** [google/roboto#150] opened 2016-01-21 23:38 UTC
Here's the error. Tried to compile on Mac OS X and on Ubuntu with same result.
--
Minor version in 2.1289 has too many digits and won't fit into the head table's fontRevision field; rounded to 2.129.
Traceback (most recent call last):
  File "scripts/build-v2.py", line 96, in <module>
    proj.generateFont(th.font, "%s/Thin/Regular/Th"%FAMILYNAME)
  File "/home/administrator/roboto-src/roboto/scripts/lib/fontbuild/Build.py", line 174, in generateFont
    saveOTF(newFont, otfName)
  File "/home/administrator/roboto-src/roboto/scripts/lib/fontbuild/Build.py", line 292, in saveOTF
    kernWriter=RobotoKernWriter)
  File "build/bdist.linux-x86_64/egg/ufo2ft/__init__.py", line 29, in compileOTF
  File "build/bdist.linux-x86_64/egg/ufo2ft/__init__.py", line 18, in _compile
  File "build/bdist.linux-x86_64/egg/ufo2ft/makeotfParts.py", line 27, in compile
  File "build/bdist.linux-x86_64/egg/ufo2ft/makeotfParts.py", line 166, in setupFile_featureTables
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/feaLib/builder.py", line 14, in addOpenTypeFeatures
    builder.build()
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/feaLib/builder.py", line 63, in build
    gdef = self.buildGDEF()
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/feaLib/builder.py", line 164, in buildGDEF
    gdef.GlyphClassDef = self.buildGDEFGlyphClassDef_()
  File "/usr/local/lib/python2.7/dist-packages/FontTools/fontTools/feaLib/builder.py", line 195, in buildGDEFGlyphClassDef_
    (glyph, name1, name2), markClassDef.location)
fontTools.feaLib.error.FeatureLibError: /tmp/tmpADNADS:7731:5: Glyph uni1ABC cannot be both in markClass @MC_mark_parent_top and @MC_mark_top
make: *** [v2] Error 1

**Comment by jamesgk** [comment] 2016-01-28 20:58
Thank you for the bug report! This is a duplicate of https://github.com/behdad/fonttools/issues/453

**Closed by jamesgk** 2016-01-28 20:58 UTC

**Comment by jamesgk** [comment] 2016-03-18 00:03
Note: this should be fixed upstream. Thanks again for the report.
