### ISSUE TITLE
Consider dropping Name IDs with pid=1 for all or certain targets? 

### ISSUE THREAD

**Issue by jungshik** [google/roboto#82] opened 2015-08-11 18:22 UTC
Spun off from #68 

The name table of hinted Roboto seems to always have name ids with PID=1. Dropping them will save the space a tiny bit. 

/cc @roozbehp @davelab6

**Comment by jamesgk** [comment] 2015-08-11 18:27
Duplicate of #77

**Closed by jamesgk** 2015-08-11 18:27 UTC
